// Data katalog resep Indonesia (autentik) untuk di-seed.
// isPremium: true = resep "exclusive", hanya bisa dibuka subscriber (PRO).
// imageUrl sengaja null — bisa diisi nanti (FE bundle aset / Supabase Storage).

export interface CatalogSeed {
    name: string;
    description: string;
    category: string;
    ingredients: string[];
    directions: string[];
    isPremium: boolean;
}

export const catalogRecipes: CatalogSeed[] = [
    {
        name: "Nasi Goreng Kampung",
        description: "Nasi goreng sederhana ala rumahan dengan cabai dan kecap, paling pas pakai nasi sisa semalam.",
        category: "Makanan Utama",
        isPremium: false,
        ingredients: [
            "Nasi putih 1 piring (sebaiknya nasi dingin)",
            "Bawang merah 3 siung, iris",
            "Bawang putih 2 siung, cincang",
            "Cabai rawit 5 buah, iris sesuai selera",
            "Telur 1 butir",
            "Kecap manis 1 sdm",
            "Garam dan kaldu bubuk secukupnya",
            "Minyak goreng 2 sdm",
            "Daun bawang, iris (opsional)",
        ],
        directions: [
            "Panaskan minyak, tumis bawang merah, bawang putih, dan cabai hingga harum.",
            "Sisihkan tumisan ke pinggir wajan, orak-arik telur sampai matang.",
            "Masukkan nasi, aduk rata dengan bumbu dan telur.",
            "Tambahkan kecap manis, garam, dan kaldu bubuk, aduk hingga merata.",
            "Masak sambil diaduk hingga nasi sedikit kering, taburi daun bawang, sajikan.",
        ],
    },
    {
        name: "Telur Balado",
        description: "Telur rebus yang digoreng lalu dibalut sambal merah pedas manis. Lauk andalan sejuta umat.",
        category: "Makanan Utama",
        isPremium: false,
        ingredients: [
            "Telur ayam 6 butir, rebus dan kupas",
            "Cabai merah keriting 8 buah",
            "Cabai rawit 5 buah (opsional)",
            "Bawang merah 5 siung",
            "Bawang putih 2 siung",
            "Tomat 1 buah",
            "Garam dan gula secukupnya",
            "Minyak goreng secukupnya",
        ],
        directions: [
            "Goreng telur rebus sebentar hingga kulitnya sedikit kering, sisihkan.",
            "Haluskan cabai, bawang merah, bawang putih, dan tomat.",
            "Tumis bumbu halus dengan sedikit minyak hingga matang dan harum.",
            "Bumbui garam dan gula, koreksi rasa.",
            "Masukkan telur, aduk hingga bumbu menyelimuti telur, sajikan.",
        ],
    },
    {
        name: "Capcay Kuah",
        description: "Tumis aneka sayuran berkuah gurih yang ringan dan menyehatkan, cepat dibuat.",
        category: "Makanan Utama",
        isPremium: false,
        ingredients: [
            "Sawi putih, wortel, kembang kol secukupnya",
            "Bakso atau ayam 100 gr (opsional)",
            "Bawang putih 3 siung, cincang",
            "Bawang bombay 1/2 buah, iris",
            "Saus tiram 2 sdm",
            "Garam, gula, dan merica secukupnya",
            "Tepung maizena 1 sdt, larutkan dengan air",
            "Air 400 ml",
            "Minyak untuk menumis",
        ],
        directions: [
            "Tumis bawang putih dan bawang bombay hingga harum.",
            "Masukkan ayam atau bakso, masak hingga berubah warna.",
            "Tuang air, masukkan wortel dan kembang kol, masak hingga setengah empuk.",
            "Masukkan sawi, saus tiram, garam, gula, dan merica.",
            "Kentalkan dengan larutan maizena, aduk hingga mengental, angkat.",
        ],
    },
    {
        name: "Tumis Kangkung Terasi",
        description: "Kangkung tumis cepat dengan terasi bakar, harum dan segar dengan sentuhan pedas.",
        category: "Sayur & Nabati",
        isPremium: false,
        ingredients: [
            "Kangkung 1 ikat, petik dan cuci",
            "Bawang merah 3 siung, iris",
            "Bawang putih 2 siung, iris",
            "Cabai merah 3 buah, iris",
            "Terasi 1 sdt, bakar",
            "Saus tiram 1 sdm",
            "Garam dan gula secukupnya",
            "Sedikit air",
            "Minyak untuk menumis",
        ],
        directions: [
            "Panaskan minyak, tumis bawang merah, bawang putih, dan cabai hingga layu.",
            "Masukkan terasi, aduk hingga harum.",
            "Masukkan kangkung, aduk cepat dengan api besar.",
            "Tambahkan saus tiram, garam, gula, dan sedikit air.",
            "Masak sebentar hingga kangkung layu tapi masih hijau segar, angkat.",
        ],
    },
    {
        name: "Tempe Orek Kering",
        description: "Tempe potong korek api dimasak kecap hingga kering manis dan sedikit karamel. Tahan lama.",
        category: "Sayur & Nabati",
        isPremium: false,
        ingredients: [
            "Tempe 1 papan, potong korek api",
            "Bawang merah 4 siung, iris",
            "Bawang putih 2 siung, iris",
            "Cabai merah 3 buah, iris",
            "Kecap manis 3 sdm",
            "Gula merah 1 sdm, sisir",
            "Daun salam 1 lembar",
            "Garam secukupnya",
            "Minyak goreng secukupnya",
        ],
        directions: [
            "Goreng tempe hingga setengah kering, tiriskan.",
            "Tumis bawang merah, bawang putih, cabai, dan daun salam hingga harum.",
            "Masukkan gula merah dan kecap manis, aduk hingga larut.",
            "Masukkan tempe goreng, aduk rata hingga bumbu meresap.",
            "Masak hingga kering dan agak mengilap, angkat.",
        ],
    },
    {
        name: "Sayur Asem",
        description: "Sup sayur berkuah asam segar khas rumahan dengan campuran labu siam, jagung, dan melinjo.",
        category: "Sayur & Nabati",
        isPremium: false,
        ingredients: [
            "Labu siam 1 buah, potong dadu",
            "Kacang panjang 5 batang, potong",
            "Jagung manis 1 buah, potong",
            "Melinjo dan daun melinjo segenggam",
            "Asam jawa 1 sdm",
            "Bawang merah 5 siung",
            "Bawang putih 3 siung",
            "Cabai merah 2 buah",
            "Gula merah dan garam secukupnya",
            "Air 1 liter",
        ],
        directions: [
            "Haluskan bawang merah, bawang putih, dan cabai.",
            "Didihkan air, masukkan bumbu halus dan jagung, masak hingga jagung empuk.",
            "Masukkan melinjo, labu siam, dan kacang panjang.",
            "Tambahkan asam jawa, gula merah, dan garam.",
            "Masak hingga semua sayuran matang, koreksi rasa asam-manis-asin, angkat.",
        ],
    },
    {
        name: "Pisang Goreng",
        description: "Pisang berbalut tepung renyah, camilan sore klasik yang nikmat selagi hangat.",
        category: "Camilan & Jajanan Pasar",
        isPremium: false,
        ingredients: [
            "Pisang kepok atau uli 6 buah",
            "Tepung terigu 150 gr",
            "Tepung beras 2 sdm",
            "Gula pasir 1 sdm",
            "Garam sejumput",
            "Air secukupnya",
            "Minyak untuk menggoreng",
        ],
        directions: [
            "Campur tepung terigu, tepung beras, gula, dan garam.",
            "Tuang air sedikit demi sedikit hingga adonan kental.",
            "Kupas dan belah pisang, celupkan ke adonan.",
            "Goreng dalam minyak panas hingga kuning keemasan.",
            "Tiriskan dan sajikan hangat.",
        ],
    },
    {
        name: "Bakwan Sayur",
        description: "Gorengan sayur renyah berisi wortel dan kol, cocok jadi camilan atau teman makan nasi.",
        category: "Camilan & Jajanan Pasar",
        isPremium: false,
        ingredients: [
            "Wortel 1 buah, serut",
            "Kol 1/4 bagian, iris halus",
            "Daun bawang 2 batang, iris",
            "Tepung terigu 150 gr",
            "Bawang putih 2 siung, haluskan",
            "Garam, merica, dan kaldu bubuk secukupnya",
            "Air secukupnya",
            "Minyak untuk menggoreng",
        ],
        directions: [
            "Campur semua sayuran dengan tepung terigu.",
            "Masukkan bawang putih halus, garam, merica, dan kaldu bubuk.",
            "Tuang air sedikit demi sedikit hingga adonan bisa dibentuk.",
            "Goreng sesendok adonan dalam minyak panas hingga kecokelatan.",
            "Tiriskan dan sajikan.",
        ],
    },
    {
        name: "Es Teh Manis",
        description: "Teh manis dingin penyegar dahaga, minuman wajib di meja makan keluarga Indonesia.",
        category: "Minuman",
        isPremium: false,
        ingredients: [
            "Teh celup atau teh tubruk 2 kantong",
            "Gula pasir 3 sdm",
            "Air panas 300 ml",
            "Es batu secukupnya",
            "Air dingin secukupnya",
        ],
        directions: [
            "Seduh teh dengan air panas, diamkan 3-5 menit.",
            "Angkat kantong teh, masukkan gula, aduk hingga larut.",
            "Tuang ke gelas berisi es batu.",
            "Tambahkan air dingin sesuai selera, aduk, sajikan.",
        ],
    },
    {
        name: "Wedang Jahe",
        description: "Minuman jahe hangat dengan gula merah dan serai, menghangatkan badan di malam hari.",
        category: "Minuman",
        isPremium: false,
        ingredients: [
            "Jahe 2 ruas, bakar dan memarkan",
            "Gula merah 50 gr",
            "Serai 1 batang, memarkan",
            "Daun pandan 1 lembar",
            "Air 500 ml",
        ],
        directions: [
            "Didihkan air bersama jahe, serai, dan pandan.",
            "Masukkan gula merah, masak hingga larut.",
            "Kecilkan api, masak 5-10 menit agar aroma jahe keluar.",
            "Saring dan sajikan selagi hangat.",
        ],
    },
    {
        name: "Sambal Terasi",
        description: "Sambal terasi matang yang harum dan pedas, pendamping wajib lalapan dan ayam goreng.",
        category: "Sambal & Bumbu Dasar",
        isPremium: false,
        ingredients: [
            "Cabai merah keriting 10 buah",
            "Cabai rawit 8 buah",
            "Bawang merah 4 siung",
            "Bawang putih 2 siung",
            "Tomat 1 buah",
            "Terasi 1 sdt, bakar",
            "Garam dan gula secukupnya",
            "Minyak untuk menumis",
        ],
        directions: [
            "Goreng atau rebus cabai, bawang, dan tomat sebentar.",
            "Ulek kasar bersama terasi, garam, dan gula.",
            "Panaskan sedikit minyak, tumis sambal hingga matang dan harum.",
            "Koreksi rasa, angkat dan sajikan.",
        ],
    },
    {
        name: "Sambal Bawang",
        description: "Sambal mentah pedas dengan siraman minyak panas, simpel tapi nampol.",
        category: "Sambal & Bumbu Dasar",
        isPremium: false,
        ingredients: [
            "Cabai rawit merah 15 buah",
            "Bawang putih 4 siung",
            "Bawang merah 2 siung",
            "Garam secukupnya",
            "Penyedap secukupnya (opsional)",
            "Minyak panas 3 sdm",
        ],
        directions: [
            "Ulek cabai rawit, bawang putih, dan bawang merah hingga kasar.",
            "Tambahkan garam dan penyedap.",
            "Panaskan minyak hingga benar-benar panas.",
            "Siramkan minyak panas ke atas sambal, aduk rata, sajikan.",
        ],
    },
    {
        name: "Rendang Daging Sapi",
        description: "Rendang asli Minang: daging dimasak perlahan dalam santan dan rempah hingga kering dan hitam pekat.",
        category: "Makanan Utama",
        isPremium: true,
        ingredients: [
            "Daging sapi 500 gr, potong kotak",
            "Santan dari 1 butir kelapa",
            "Cabai merah keriting 10 buah",
            "Bawang merah 8 siung",
            "Bawang putih 4 siung",
            "Jahe, lengkuas, dan kunyit masing-masing 2 cm",
            "Serai 2 batang, memarkan",
            "Daun jeruk 4 lembar",
            "Daun kunyit 1 lembar",
            "Garam dan gula secukupnya",
        ],
        directions: [
            "Haluskan cabai, bawang merah, bawang putih, jahe, dan kunyit.",
            "Tumis bumbu halus bersama serai, daun jeruk, dan daun kunyit hingga harum.",
            "Masukkan daging, aduk hingga berubah warna.",
            "Tuang santan, masak dengan api kecil sambil sesekali diaduk agar santan tidak pecah.",
            "Masak terus 3-4 jam hingga santan menyusut, mengental, dan berwarna cokelat pekat, angkat.",
        ],
    },
    {
        name: "Soto Ayam Lamongan",
        description: "Soto ayam kuah kuning bening khas Lamongan, lengkap dengan taburan koya gurih.",
        category: "Makanan Utama",
        isPremium: true,
        ingredients: [
            "Ayam 1/2 ekor",
            "Bawang putih 4 siung",
            "Bawang merah 6 siung",
            "Kunyit 2 cm dan jahe 2 cm",
            "Kemiri 3 butir",
            "Serai 1 batang dan daun jeruk",
            "Soun, tauge, kol, dan telur rebus untuk pelengkap",
            "Koya (kerupuk udang dan bawang putih goreng dihaluskan)",
            "Garam, merica, dan gula secukupnya",
        ],
        directions: [
            "Rebus ayam hingga empuk, ambil kaldunya, lalu suwir dagingnya.",
            "Haluskan bawang, kunyit, jahe, dan kemiri, tumis bersama serai dan daun jeruk hingga harum.",
            "Masukkan tumisan ke dalam kaldu, bumbui garam, merica, dan gula.",
            "Masak hingga mendidih dan bumbu meresap.",
            "Tata soun, tauge, kol, telur, dan ayam suwir di mangkuk, siram kuah, taburi koya, sajikan.",
        ],
    },
    {
        name: "Ayam Goreng Lengkuas",
        description: "Ayam ungkep bumbu kuning digoreng renyah dengan serundeng lengkuas yang gurih.",
        category: "Makanan Utama",
        isPremium: true,
        ingredients: [
            "Ayam 1 ekor, potong",
            "Lengkuas 5 cm, parut",
            "Bawang putih 5 siung",
            "Kunyit 3 cm",
            "Kemiri 3 butir",
            "Ketumbar 1 sdt",
            "Serai 2 batang, memarkan",
            "Daun salam 2 lembar",
            "Garam secukupnya",
            "Minyak untuk menggoreng",
        ],
        directions: [
            "Haluskan bawang putih, kunyit, kemiri, dan ketumbar.",
            "Rebus ayam dengan bumbu halus, lengkuas parut, serai, daun salam, dan garam.",
            "Masak hingga air menyusut dan bumbu meresap, sisihkan serundeng lengkuasnya.",
            "Goreng ayam hingga kecokelatan.",
            "Goreng sisa bumbu lengkuas hingga kering sebagai taburan, sajikan bersama ayam.",
        ],
    },
    {
        name: "Perkedel Kentang",
        description: "Perkedel kentang lembut di dalam, gurih dari bawang goreng, pendamping soto atau nasi.",
        category: "Camilan & Jajanan Pasar",
        isPremium: true,
        ingredients: [
            "Kentang 500 gr, kupas",
            "Bawang merah 4 siung, goreng",
            "Bawang putih 2 siung, goreng",
            "Daun bawang dan seledri, iris",
            "Telur 1 butir untuk pelapis",
            "Garam, merica, dan pala secukupnya",
            "Minyak untuk menggoreng",
        ],
        directions: [
            "Goreng atau kukus kentang hingga empuk, lalu haluskan.",
            "Haluskan bawang merah dan bawang putih goreng, campur ke kentang.",
            "Masukkan daun bawang, seledri, garam, merica, dan pala, aduk rata.",
            "Bentuk bulat pipih, celupkan ke kocokan telur.",
            "Goreng hingga kuning keemasan, tiriskan, sajikan.",
        ],
    },
];
